---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.3.3"}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - role[lamp-vagrant]
  - name: php5
    run_list:
      - role
