language: ruby
gemfile:
   - test/support/Gemfile
rvm:
  - 2.1.7
sudo: required
dist: trusty
env:
  - RUNLIST=lamp.json
before_install:
  - "wget http://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chefdk_0.3.0-1_amd64.deb"
  - "sudo dpkg -i chefdk_0.3.0-1_amd64.deb"
  - "sudo touch /.dockerenv"
script:
  - bundle exec rake knife
  - bundle exec rake foodcritic
  - bundle exec rake solo

after_failure: "sudo cat /var/log/php5-fpm.log"